### ISSUE TITLE
App name/image/  on installed apps view?

### ISSUE THREAD

**Issue by manugarri** [whitewhidow/quest-sidenoder#3]
Right now the *Installed apps* tab only shows the app ids. 

![image](https://user-images.githubusercontent.com/3670355/100611857-e7b43000-3309-11eb-84d8-61c89c10e771.png)

It would be useful to see on this tab the app name and image when available the same way as its done with the mount

**Comment by whitewhidow** [comment]
the PR attached should show appnames after clicking "click to check mount for updates" (not on the regular "installed apps" list, since i dont have that data available at that point (i dont have a hmd atm, so i cannot test the response of `adb shell dumpsys package xxx`  ...  feel free to attach it here so i can see if it contains the appname)
