### ISSUE TITLE
Cannot enter directories that have single-quotes

### ISSUE THREAD

**Issue by colthreepv** [whitewhidow/quest-sidenoder#35]
**Describe the bug**
Cannot enter directories that have single-quotes, example: `My_mother's_gift`

**To Reproduce**
1. Click on directory with single-quotes
2. Nothing happens

**Expected behavior**
Directory to open

**Desktop (please complete the following information):**
 - OS: Windows
 - Running via binary
 - Version: v0.0.7-alpha

**Comment by whitewhidow** [comment]
Can you run using npm by chance ?   Instead of using a precompiled binary ?
IF so, would you mind pulling and running the current dev build, and verifying if this issue is indeed fixed?
I verified that navigating into a directory with a single quote now works, but due to lack of hmd atm i cannot verify if the actual sideloading/updating/unintalling process works properly using APK names that hold a single quote.

Any chance you could verify ?    Thx in advance

**Comment by colthreepv** [comment]
Yes, tested `development` branch and could navigate inside single-quote directories, and also upload APKs that have single-quotes in it 😉

**Comment by whitewhidow** [comment]
thx, will close this ticket as soon as it is merged to main

**Comment by whitewhidow** [comment]
fixed in 
https://github.com/whitewhidow/quest-sidenoder/releases/tag/0.0.9-DEV
