### ISSUE TITLE
Local caching of downloaded mount files to speed up multiple headset updates on the same machine.

### ISSUE THREAD

**Issue by VIPKaiser** [whitewhidow/quest-sidenoder#41]
Updating multiple headsets causes re-downloading from the mount. If you could allow an option to retain the downloads (even temporarily) and check this folder before redownloading it would speed up updating multiple headsets massively.

**Comment by whitewhidow** [comment]
The copying to a specific folder, instead of installing apk/copying obb straight from the mount, is already on the plan, as this speeds up the apk and obb part massively.
In addition i will add an option to settings, to retain these files, and will check for their presence, before dl'ing them again.

**Comment by whitewhidow** [comment]
a copy of the apk's and obb's (aswell as restore data) will be left in the systems tmp folder, and reused if sideloaded a second time.
(toggles for deletion of these files and maybe option to change path, still to be added to settings page )
