### ISSUE TITLE
Updating app leads to loss of savedata

### ISSUE THREAD

**Issue by ov3rk1ll** [whitewhidow/quest-sidenoder#9]
After a update of a game, all my progress and settings were lost.

There version of sidenoder I was running at the time did execute ` adb shell pm uninstall -k XXX` before installing the update so I'd imagine that it has something to do with that. Even with the `-k` flag, it seems like some data still gets removed.

My suggestion would be to not run uninstall for an update and instead add the `-r` (for replace) flag to the `adb install` command.  
I don't really have a good way to fully test this right now so I can't 100% say if that wont cause other issues.

I the uninstall there for a specific reason? Have you run into any issues in the past that required the uninstall beforehand?

**Comment by whitewhidow** [comment]
the reason that i dont just do install with -r, is because that fails when the app is signed by a different developer. (which btw STILL turns out to be the case EVEN uninstall -k) 
So for now i have switched it to straight up uninstall, and install the new one.
Its basically shoosing between 2 shitty choices, i can either make it :
1. uninstall, and reinstall, will never fail, but can lose data
2. dont uninstall and install with -r switch, which might cause some updates to fail

currently i am doing nr1, i will soon switch this over to nr2, and inform the user if it is failing due to signature mismatch

**Comment by ov3rk1ll** [comment]
I see. It's strange that the signature would change at all but I guess that has something to do with patching some apps.

Ideally the installation is done with -r. If that fails with the "signatures do not match", a message is shown telling the user that the app has to be uninstalled first which can cause data loss so at lease there is some kind of warning and the user can try to manually back up game files.

**Comment by whitewhidow** [comment]
closing as this should be fixed in v0.0.4-alpha-DEV3
